name: "Analyse code with sonar"

inputs:
  solution_path:
    description: "Path to the project to run commands"
    required: true

runs:
  using: "composite"
  steps:
  - name: SonarCloud Scan
    uses: SonarSource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    with:
      projectBaseDir: ${{ inputs.solution_path }}
