name: My Test Monorepo Project
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  ReactScan:
    name: ReactScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Composite/Sonar
        with:
          solution_path: PMCS/Client/react-pmcs
  AuthServiceScan:
    name: AuthServiceScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Composite/Sonar
        with:
          solution_path: PMCS/Services/AuthorizationService
  PetServiceScan:
    name: PetServiceScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Composite/Sonar
        with:
          solution_path: PMCS/Services/PetService
  ScheduleServiceScan:
    name: ScheduleServiceScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Composite/Sonar
        with:
          solution_path: PMCS/Services/ScheduleService
  NotificationServiceScan:
    name: NotificationServiceScan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/Composite/Sonar
        with:
          solution_path: PMCS/Services/NotificationService
          