name: .NET
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  BuildPetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/PetService/PMCS.sln
    - name: Test
      uses: ./.github/workflows/Composite/Test
      with:
        project_path: PMCS/Services/PetService/PMCS.sln
  BuildNotificationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/NotificationService/NotificationService.sln
    - name: Test
      uses: ./.github/workflows/Composite/Test
      with:
        project_path: PMCS/Services/NotificationService/NotificationService.sln
  BuildAuthorizationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/AuthorizationService/AuthorizationService.sln
    - name: Test
      uses: ./.github/workflows/Composite/Test
      with:
        project_path: PMCS/Services/AuthorizationService/AuthorizationService.sln
  BuildScheduleService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/ScheduleService/ScheduleService.sln
    - name: Test
      uses: ./.github/workflows/Composite/Test
      with:
        project_path: PMCS/Services/ScheduleService/ScheduleService.sln
  BuildGateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Gateway/Gateway.sln
    - name: Test
      uses: ./.github/workflows/Composite/Test
      with:
        project_path: PMCS/Gateway/Gateway.sln