name: .NET
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  BuildAuthorizationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Authorization Microservice
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/AuthorizationService/AuthorizationService.sln
  BuildNotificationService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Notifications Microservice
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/NotificationService/NotificationService.sln
  BuildScheduleService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Schedule Microservice
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/ScheduleService/ScheduleService.sln
  BuildPetService:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Pet Microservice
      uses: ./.github/workflows/Composite/Build
      with:
        project_path: PMCS/Services/PetService/PMCS.sln
