name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore PMCS/PMCS.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore PMCS/PMCS.sln
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal PMCS/PMCS.sln
